/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto_cliente;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author andro
 */

import proyecto_cliente.Modulo_Productos_Ventas.Modulo_Productos;
import proyecto_cliente.Modulo_Productos_Ventas.clProductos;
import proyecto_cliente.Modulo_Productos_Ventas.Almacenamiento_Productos;
import proyecto_cliente.Modulo_Productos_Ventas.Modulo_Productos;
public class _menu_ extends javax.swing.JFrame {
private Modulo_Productos moduloProductos;
    /**
     * Creates new form NewJFrame
     */
  public _menu_() {
        initComponents();
        moduloProductos = new Modulo_Productos("ID_de_tu_menu");
        
        // Vincula los botones con las pestañas correspondientes
        boton1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Productos.setSelectedComponent(tab1_Cliente);
            }
        });

        boton2.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Productos.setSelectedComponent(tab2_Empleado);
            }
        });

        boton3.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Productos.setSelectedComponent(tab3_Producto);
            }
        });

        boton4.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Productos.setSelectedComponent(tab4_Ventas);
            }
        });

        boton5.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Productos.setSelectedComponent(tab5_Provedores);
            }
        });
        
        // Asocia acciones a los botones de operaciones con productos
        Agregar_Producto.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                NuevoProductoDialog dialog = new NuevoProductoDialog(_menu_.this, true, moduloProductos);
                dialog.setVisible(true);
            }
        });

        Listar_Producto.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                ArrayList<clProductos> productos = moduloProductos.getAnimalitos();
                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                model.setRowCount(0);

                for (clProductos producto : productos) {
                    Object[] rowData = {producto.getNombre(), producto.getID(), producto.getPrecio(), producto.getCantidad()};
                    model.addRow(rowData);
                }
            }
        });

        Vender_Producto.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                VenderProductoDialog dialog = new VenderProductoDialog(_menu_.this, true, moduloProductos);
                dialog.setVisible(true);
            }
        });

        Eliminar_Producto.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                EliminarProductoDialog dialog = new EliminarProductoDialog(_menu_.this, true, moduloProductos);
                dialog.setVisible(true);
            }
        });
    }

        
     
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
        
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        barra_horizontal = new javax.swing.JPanel();
        barra_vertical = new javax.swing.JPanel();
        boton1 = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        boton2 = new javax.swing.JButton();
        boton3 = new javax.swing.JButton();
        boton4 = new javax.swing.JButton();
        boton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Productos = new javax.swing.JTabbedPane();
        tab1_Cliente = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        tab2_Empleado = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        tab3_Producto = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Table_Productos = new javax.swing.JTable();
        Agregar_Producto = new javax.swing.JButton();
        Actualizar_Producto = new javax.swing.JButton();
        Eliminar_Producto = new javax.swing.JButton();
        Buscar_Producto_id = new javax.swing.JButton();
        Listar_Producto = new javax.swing.JButton();
        Vender_Producto = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        tab4_Ventas = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        tab5_Provedores = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        barra_horizontal.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout barra_horizontalLayout = new javax.swing.GroupLayout(barra_horizontal);
        barra_horizontal.setLayout(barra_horizontalLayout);
        barra_horizontalLayout.setHorizontalGroup(
            barra_horizontalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 970, Short.MAX_VALUE)
        );
        barra_horizontalLayout.setVerticalGroup(
            barra_horizontalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel1.add(barra_horizontal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 50));

        barra_vertical.setBackground(new java.awt.Color(204, 204, 255));

        boton1.setText("Modulo Cliente");

        salir.setBackground(new java.awt.Color(153, 153, 255));
        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        boton2.setText("Modulo Empleado");

        boton3.setText("Modulo Producto");

        boton4.setText("Modulo Ventas");

        boton5.setText("Modulo Provedores");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_cliente/imagenes/icono.png"))); // NOI18N

        jLabel4.setText("Menu");

        javax.swing.GroupLayout barra_verticalLayout = new javax.swing.GroupLayout(barra_vertical);
        barra_vertical.setLayout(barra_verticalLayout);
        barra_verticalLayout.setHorizontalGroup(
            barra_verticalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barra_verticalLayout.createSequentialGroup()
                .addGroup(barra_verticalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(barra_verticalLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(barra_verticalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(barra_verticalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(boton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(boton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(boton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(boton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(boton5, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))))
                    .addGroup(barra_verticalLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(barra_verticalLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jLabel4)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        barra_verticalLayout.setVerticalGroup(
            barra_verticalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barra_verticalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(boton1)
                .addGap(27, 27, 27)
                .addComponent(boton2)
                .addGap(29, 29, 29)
                .addComponent(boton3)
                .addGap(27, 27, 27)
                .addComponent(boton4)
                .addGap(35, 35, 35)
                .addComponent(boton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(barra_vertical, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 210, 580));

        tab1_Cliente.setBackground(new java.awt.Color(255, 204, 204));
        tab1_Cliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_cliente/imagenes/Purple Badge Car Wash Logo.jpg"))); // NOI18N
        tab1_Cliente.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 454, 156));

        jButton1.setText("jButton1");
        tab1_Cliente.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 176, -1, -1));

        jLabel3.setText("Cliente");
        tab1_Cliente.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(571, 27, -1, -1));

        jButton2.setText("jButton2");
        tab1_Cliente.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 176, -1, -1));

        jButton3.setText("jButton3");
        tab1_Cliente.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 176, -1, -1));

        jButton4.setText("jButton4");
        tab1_Cliente.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 176, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        tab1_Cliente.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 219, 731, 334));

        jButton5.setText("jButton5");
        tab1_Cliente.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(552, 176, -1, -1));

        Productos.addTab("tab1", tab1_Cliente);

        tab2_Empleado.setBackground(new java.awt.Color(255, 255, 204));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_cliente/imagenes/Purple Badge Car Wash Logo.jpg"))); // NOI18N

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jButton6.setText("jButton6");

        jButton7.setText("jButton7");

        jButton8.setText("jButton8");

        jButton9.setText("jButton9");

        jButton10.setText("jButton10");

        javax.swing.GroupLayout tab2_EmpleadoLayout = new javax.swing.GroupLayout(tab2_Empleado);
        tab2_Empleado.setLayout(tab2_EmpleadoLayout);
        tab2_EmpleadoLayout.setHorizontalGroup(
            tab2_EmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab2_EmpleadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tab2_EmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tab2_EmpleadoLayout.createSequentialGroup()
                        .addGroup(tab2_EmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tab2_EmpleadoLayout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())
                    .addGroup(tab2_EmpleadoLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jButton6)
                        .addGap(18, 18, 18)
                        .addComponent(jButton7)
                        .addGap(18, 18, 18)
                        .addComponent(jButton8)
                        .addGap(18, 18, 18)
                        .addComponent(jButton9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 181, Short.MAX_VALUE)
                        .addComponent(jButton10)
                        .addGap(107, 107, 107))))
        );
        tab2_EmpleadoLayout.setVerticalGroup(
            tab2_EmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab2_EmpleadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(tab2_EmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton7)
                    .addComponent(jButton8)
                    .addComponent(jButton9)
                    .addComponent(jButton10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Productos.addTab("tab2", tab2_Empleado);

        tab3_Producto.setBackground(new java.awt.Color(204, 255, 204));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_cliente/imagenes/Purple Badge Car Wash Logo.jpg"))); // NOI18N

        Table_Productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(Table_Productos);

        Agregar_Producto.setText("Agregar");

        Actualizar_Producto.setText("Actualizar");

        Eliminar_Producto.setText("Eliminar");

        Buscar_Producto_id.setText("Buscar");

        Listar_Producto.setText("Listar");

        Vender_Producto.setText("Vender");

        jLabel9.setText("Productos");

        javax.swing.GroupLayout tab3_ProductoLayout = new javax.swing.GroupLayout(tab3_Producto);
        tab3_Producto.setLayout(tab3_ProductoLayout);
        tab3_ProductoLayout.setHorizontalGroup(
            tab3_ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab3_ProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tab3_ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab3_ProductoLayout.createSequentialGroup()
                        .addComponent(jScrollPane3)
                        .addGap(36, 36, 36))
                    .addGroup(tab3_ProductoLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(102, 102, 102)
                        .addComponent(jLabel9)
                        .addContainerGap(133, Short.MAX_VALUE))
                    .addGroup(tab3_ProductoLayout.createSequentialGroup()
                        .addComponent(Agregar_Producto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Actualizar_Producto)
                        .addGap(18, 18, 18)
                        .addComponent(Eliminar_Producto)
                        .addGap(18, 18, 18)
                        .addComponent(Buscar_Producto_id)
                        .addGap(18, 18, 18)
                        .addComponent(Vender_Producto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Listar_Producto)
                        .addGap(114, 114, 114))))
        );
        tab3_ProductoLayout.setVerticalGroup(
            tab3_ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab3_ProductoLayout.createSequentialGroup()
                .addGroup(tab3_ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tab3_ProductoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tab3_ProductoLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tab3_ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Agregar_Producto)
                    .addComponent(Actualizar_Producto)
                    .addComponent(Eliminar_Producto)
                    .addComponent(Buscar_Producto_id)
                    .addComponent(Listar_Producto)
                    .addComponent(Vender_Producto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Productos.addTab("tab3", tab3_Producto);

        tab4_Ventas.setBackground(new java.awt.Color(204, 255, 255));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_cliente/imagenes/Purple Badge Car Wash Logo.jpg"))); // NOI18N

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        jButton16.setText("jButton16");

        jButton17.setText("jButton17");

        jButton18.setText("jButton18");

        jButton19.setText("jButton19");

        jButton20.setText("jButton20");

        javax.swing.GroupLayout tab4_VentasLayout = new javax.swing.GroupLayout(tab4_Ventas);
        tab4_Ventas.setLayout(tab4_VentasLayout);
        tab4_VentasLayout.setHorizontalGroup(
            tab4_VentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab4_VentasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tab4_VentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tab4_VentasLayout.createSequentialGroup()
                        .addGroup(tab4_VentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4)
                            .addGroup(tab4_VentasLayout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(tab4_VentasLayout.createSequentialGroup()
                        .addComponent(jButton16)
                        .addGap(18, 18, 18)
                        .addComponent(jButton17)
                        .addGap(18, 18, 18)
                        .addComponent(jButton18)
                        .addGap(18, 18, 18)
                        .addComponent(jButton19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 179, Short.MAX_VALUE)
                        .addComponent(jButton20)
                        .addGap(95, 95, 95))))
        );
        tab4_VentasLayout.setVerticalGroup(
            tab4_VentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab4_VentasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tab4_VentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton16)
                    .addComponent(jButton17)
                    .addComponent(jButton18)
                    .addComponent(jButton19)
                    .addComponent(jButton20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Productos.addTab("tab4", tab4_Ventas);

        tab5_Provedores.setBackground(new java.awt.Color(255, 102, 102));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_cliente/imagenes/Purple Badge Car Wash Logo.jpg"))); // NOI18N

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jTable5);

        jButton21.setText("jButton21");

        jButton22.setText("jButton22");

        jButton23.setText("jButton23");

        jButton24.setText("jButton24");

        jButton25.setText("jButton25");

        javax.swing.GroupLayout tab5_ProvedoresLayout = new javax.swing.GroupLayout(tab5_Provedores);
        tab5_Provedores.setLayout(tab5_ProvedoresLayout);
        tab5_ProvedoresLayout.setHorizontalGroup(
            tab5_ProvedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab5_ProvedoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tab5_ProvedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tab5_ProvedoresLayout.createSequentialGroup()
                        .addGroup(tab5_ProvedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5)
                            .addGroup(tab5_ProvedoresLayout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(tab5_ProvedoresLayout.createSequentialGroup()
                        .addComponent(jButton21)
                        .addGap(18, 18, 18)
                        .addComponent(jButton22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton23)
                        .addGap(18, 18, 18)
                        .addComponent(jButton24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 183, Short.MAX_VALUE)
                        .addComponent(jButton25)
                        .addGap(97, 97, 97))))
        );
        tab5_ProvedoresLayout.setVerticalGroup(
            tab5_ProvedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab5_ProvedoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tab5_ProvedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton21)
                    .addComponent(jButton22)
                    .addComponent(jButton23)
                    .addComponent(jButton24)
                    .addComponent(jButton25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Productos.addTab("tab5", tab5_Provedores);

        jPanel1.add(Productos, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 760, 590));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(_menu_.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(_menu_.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(_menu_.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(_menu_.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new _menu_().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Actualizar_Producto;
    private javax.swing.JButton Agregar_Producto;
    private javax.swing.JButton Buscar_Producto_id;
    private javax.swing.JButton Eliminar_Producto;
    private javax.swing.JButton Listar_Producto;
    private javax.swing.JTabbedPane Productos;
    private javax.swing.JTable Table_Productos;
    private javax.swing.JButton Vender_Producto;
    private javax.swing.JPanel barra_horizontal;
    private javax.swing.JPanel barra_vertical;
    private javax.swing.JButton boton1;
    private javax.swing.JButton boton2;
    private javax.swing.JButton boton3;
    private javax.swing.JButton boton4;
    private javax.swing.JButton boton5;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JButton salir;
    private javax.swing.JPanel tab1_Cliente;
    private javax.swing.JPanel tab2_Empleado;
    private javax.swing.JPanel tab3_Producto;
    private javax.swing.JPanel tab4_Ventas;
    private javax.swing.JPanel tab5_Provedores;
    // End of variables declaration//GEN-END:variables
}
